spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libaryBook?useSSL=false&serverTimezone=UTC
    username: root
    password: 2805
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463